=== snagappa/udg_pandora/scenes/UWSimScene.dtd
<!ELEMENT UWSimScene (oceanState?,simParams?,camera?,vehicle*,object*,rosInterfaces?)>

<!-- elementos oceanScene -->
<!ELEMENT oceanState (windx?,windy?,windSpeed?,depth?,reflectionDamping?,waveScale?,isNotChoppy?,choppyFactor?,crestFoamHeight?,oceanSurfaceHeight?,fog?,color?,attenuation?)>
<!ELEMENT simParams (disableShaders?,resw?,resh?,offsetp?,offsetr?)>
<!ELEMENT vehicle (name,file,jointValues?,position?,orientation?,virtualCamera*, rangeSensor*)>
<!ELEMENT virtualCamera (name,relativeTo,resw?,resh?,position?,orientation?,baseline?,frameId?, parameters?)>
<!ELEMENT rangeSensor (name,relativeTo,range,visible?,position?,orientation?)>
<!ELEMENT camera (freeMotion?,objectToTrack?,fov?,aspectRatio?,near?,far?,position?,lookAt?) >
<!ELEMENT object (name,file,position,orientation,offsetp?,offsetr?)>
<!ELEMENT rosInterfaces ((ROSOdomToPAT*)?, (PATToROSOdom*)?, (ArmToROSJointState*)?, (ROSJointStateToArm*)?, (VirtualCameraToROSImage*)?, (ROSImageToHUD*)?,(ROSTwistToPAT*)?, (RangeSensorToROSRange*)?, (ROSPoseToPAT*)?)>

<!-- elementos comunes -->
<!ELEMENT position (x,y,z)>
<!ELEMENT orientation (r,p,y)>
<!ELEMENT offsetp (x,y,z)>
<!ELEMENT offsetr (x,y,z)>
<!ELEMENT lookAt (x,y,z)>
<!ELEMENT color (r,g,b)>

<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>
<!ELEMENT r (#PCDATA)>
<!ELEMENT g (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT p (#PCDATA)>

<!-- elementos oceanState -->
<!ELEMENT windx (#PCDATA)>
<!ELEMENT windy (#PCDATA)>
<!ELEMENT windSpeed (#PCDATA)>
<!ELEMENT depth (#PCDATA)>
<!ELEMENT reflectionDamping (#PCDATA)>
<!ELEMENT waveScale (#PCDATA)>
<!ELEMENT isNotChoppy (#PCDATA)>
<!ELEMENT choppyFactor (#PCDATA)>
<!ELEMENT crestFoamHeight (#PCDATA)>
<!ELEMENT oceanSurfaceHeight (#PCDATA)>
<!ELEMENT fog (density,color)>
<!ELEMENT attenuation (r,g,b)>

<!ELEMENT density (#PCDATA)>

<!-- elementos simParams -->
<!ELEMENT disableShaders (#PCDATA)>
<!ELEMENT eye_in_hand (#PCDATA)>
<!ELEMENT resw (#PCDATA)>
<!ELEMENT resh (#PCDATA)>

<!--elementos camera -->
<!ELEMENT freeMotion (#PCDATA)>
<!ELEMENT fov (#PCDATA)>
<!ELEMENT aspectRatio (#PCDATA)>
<!ELEMENT near (#PCDATA)>
<!ELEMENT far (#PCDATA)>

<!ELEMENT objectToTrack (#PCDATA)>

<!-- elementos virtualCamera -->
<!ELEMENT relativeTo (#PCDATA)>
<!ELEMENT parameters (fx,fy,x0,y0,f,n,k)>

<!ELEMENT fx (#PCDATA)>
<!ELEMENT fy (#PCDATA)>
<!ELEMENT x0 (#PCDATA)>
<!ELEMENT y0 (#PCDATA)>
<!ELEMENT f (#PCDATA)>
<!ELEMENT n (#PCDATA)>
<!ELEMENT k (#PCDATA)>
<!ELEMENT baseline (#PCDATA)>
<!ELEMENT frameId (#PCDATA)>

<!--elementos rangeSensor -->
<!ELEMENT range (#PCDATA)>
<!ELEMENT visible (#PCDATA)>

<!-- elementos vehicle -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT jointValues (joint+)>

<!ELEMENT joint (#PCDATA)>

<!-- elementos rosinterfaces -->
<!ELEMENT ROSOdomToPAT (topic,vehicleName, visualize?)>
<!ELEMENT PATToROSOdom  (topic, vehicleName, rate?)>
<!ELEMENT ArmToROSJointState  (topic, vehicleName, rate?)>
<!ELEMENT ROSJointStateToArm  (topic,vehicleName)>
<!ELEMENT VirtualCameraToROSImage (cameraName,imageTopic,infoTopic,rate?)>
<!ELEMENT RangeSensorToROSRange (name,topic,rate?)>
<!ELEMENT ROSImageToHUD (width,height,posx?,posy?,scale?,imageTopic,infoTopic?)>
<!ELEMENT ROSTwistToPAT (topic,vehicleName)>
<!ELEMENT ROSPoseToPAT (topic,vehicleName)>

<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT posx (#PCDATA)>
<!ELEMENT posy (#PCDATA)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT vehicleName (#PCDATA)>
<!ELEMENT rate (#PCDATA)>
<!ELEMENT cameraName (#PCDATA)>
<!ELEMENT imageTopic (#PCDATA)>
<!ELEMENT infoTopic (#PCDATA)>
<!ELEMENT visualize (#PCDATA)>

<!-- elementos vcamtoROSImage -->
<!ELEMENT cam (#PCDATA)>
<!ELEMENT info (#PCDATA)>

=== snagappa/udg_pandora/scenes/g500ARMPandora.xml
<?xml version="1.0"?>

<!DOCTYPE UWSimScene SYSTEM "UWSimScene.dtd" >

<UWSimScene>
  <oceanState>
    <windx> 0.04 </windx>
    <windy> 0.04 </windy>
    <windSpeed> 12 </windSpeed>
    <depth> 1000 </depth>
    <reflectionDamping> 0.35 </reflectionDamping>
    <waveScale> 1e-7 </waveScale>
    <isNotChoppy> 0 </isNotChoppy>
    <choppyFactor> 2.5 </choppyFactor>
    <crestFoamHeight> 2.2 </crestFoamHeight>
    <oceanSurfaceHeight> 0 </oceanSurfaceHeight>
    <fog>
      <density> 0.1 </density>
      <color>
	<r>0</r>
	<g>0.05</g>
	<b>0.3</b>
      </color>
    </fog>
  </oceanState>
  <simParams>
    <disableShaders> 0 </disableShaders>
    <resw> 640 </resw>
    <resh> 480 </resh>
  </simParams>

  <camera>
    <freeMotion> 0 </freeMotion>
    <objectToTrack>giron500/base_link</objectToTrack>
    <fov> 60 </fov>
    <aspectRatio> 1.33 </aspectRatio>
    <near> 1 </near>
    <far> 10000 </far>
    <position>
      <!-- visio lateral esquerra-->
      <x>1.0</x>
      <y>-2.5</y>
      <z>-4</z> 
      <!-- visio des de sota-->
      <!-- <x>1.0</x>
      <y>0</y>
      <z>-6</z> -->
    </position> 
    <lookAt>
      <x>1.0</x>
      <y>0 </y>
      <z>-4.5 </z>
    </lookAt>
  </camera>

  <vehicle>
    <name>girona500</name>
    <file>data/scenes/g500ARMPandora.urdf</file>
    <jointValues>
      <joint> -0.75 </joint> <!--Brac -->
      <joint> 0.75 </joint> <!-- Ma -->
      <joint> 0.0 </joint> <!-- Support -->
      <joint> 0.0 </joint> <!-- Mou la pinsa avall jaw1 -->
      <joint> 0.0 </joint> <!-- No Fa res -->
      <joint> 0.0 </joint> <!-- No fa res -->
      <joint> 0.0 </joint> <!-- No fa res -->
     <!-- <joint> 1.57 </joint>
      <joint> 0 </joint>
      <joint> 0 </joint> -->
    </jointValues>
    <position>
      <x> 0</x>
      <y> 0 </y>
      <z> -3.5 </z>
    </position>
    <orientation>
      <r>3.1415 </r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  <virtualCamera>
    <name>bowtech</name>
    <relativeTo>base_link</relativeTo>
    <resw> 160 </resw>
    <resh> 120 </resh>
    <position>
      <x>-0.5</x>
      <y> 1 </y>
      <z> -0.2 </z>
    </position>  
  </virtualCamera>
  </vehicle>

  <rosInterfaces>
    <ROSOdomToPAT>
      <topic> /dataNavigator </topic>
      <vehicleName> girona500 </vehicleName>
    </ROSOdomToPAT>
    <PATToROSOdom>
      <topic> /uwsim/girona500_odom </topic>
      <vehicleName> girona500 </vehicleName>
    </PATToROSOdom>
    <ArmToROSJointState> 
	<topic>/uwsim/joint_state</topic>
	<vehicleName> girona500 </vehicleName>
    </ArmToROSJointState>
    <ROSJointStateToArm> 
	<topic>/uwsim/joint_state_command</topic>
	<vehicleName> girona500 </vehicleName>
    </ROSJointStateToArm>
    <VirtualCameraToROSImage> 
      <cameraName>bowtech1</cameraName>
      <imageTopic> /uwsim/camera1 </imageTopic>
      <infoTopic> /uwsim/camera1_info </infoTopic>
    </VirtualCameraToROSImage>
    <RangeSensorToROSRange>
      <name>sonar</name>
      <topic> /uwsim/g500/range </topic>
      <rate>10</rate>
    </RangeSensorToROSRange>	
  </rosInterfaces> 

</UWSimScene>

=== snagappa/udg_pandora/scenes/cirsPandora.xml
<?xml version="1.0"?>

<!DOCTYPE UWSimScene SYSTEM "UWSimScene.dtd" >

<UWSimScene>
  <oceanState>
    <windx> 0.04 </windx>
    <windy> 0.04 </windy>
    <windSpeed> 12 </windSpeed>
    <depth> 1000 </depth>
    <reflectionDamping> 0.35 </reflectionDamping>
    <waveScale> 1e-7 </waveScale>
    <isNotChoppy> 0 </isNotChoppy>
    <choppyFactor> 2.5 </choppyFactor>
    <crestFoamHeight> 2.2 </crestFoamHeight>
    <oceanSurfaceHeight> 0 </oceanSurfaceHeight>
    <fog>
      <density> 0.1 </density>
      <color>
	<r>0</r>
	<g>0.05</g>
	<b>0.3</b>
      </color>
    </fog>
    <color>
      <r>0.0</r>
      <g>0.05</g>
      <b>0.3</b>
    </color>
    <attenuation>
      <r>0.015</r>
      <g>0.0075 </g>
      <b> 0.005 </b>
    </attenuation>
  </oceanState>
  <simParams>
    <disableShaders> 0 </disableShaders>
    <resw> 800 </resw>
    <resh> 600 </resh>
    <offsetp>
      <x>0</x>
      <y>0</y>
      <z>0</z>
    </offsetp>
    <offsetr>
      <x> 3.14</x>
      <y> 0</y>
      <z> -1.57 </z>
    </offsetr>
  </simParams>
  <camera>
    <freeMotion> 1 </freeMotion>
    <objectToTrack>girona500/base_link</objectToTrack>
    <fov> 60 </fov>
    <aspectRatio> 1.33 </aspectRatio>
    <near> 1 </near>
    <far> 10000 </far>
    <position>
      <x>-5</x>
      <y>-5 </y>
      <z>8 </z>
    </position> 
    <lookAt>
      <x>0</x>
      <y>0 </y>
      <z>0 </z>
    </lookAt>
  </camera>

  <vehicle>
    <name>girona500</name>
    <file>scenes/g500ARMPandora.urdf</file>
    <jointValues>
      <joint> -0.6 </joint> <!--Brac -0.75-->
      <joint> 0.4</joint>  <!--Ma 0.75-->
      <joint> 0.0 </joint>  <!-- Support -->
      <joint> 0.0 </joint>  <!-- Mou la pinsa -->
      <!-- Son 4 por cojones -->
    </jointValues>
    <position>
      <x> 0</x>
      <y> 0 </y>
      <z> 0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
<!--    <virtualCamera>
      <name>bowtech1</name>
      <relativeTo>base</relativeTo>
      <resw> 320 </resw>
      <resh> 240 </resh>
      <position>
        <x>-0.2</x>
        <y> -0.1 </y>
        <z> 0 </z>
      </position>
      <orientation>
        <r>0</r>
        <p>0</p>
        <y>1.57 </y>
      </orientation>
    </virtualCamera>
    <virtualCamera>
      <name>bowtech2</name>
      <relativeTo>base</relativeTo>
      <resw> 320</resw>
      <resh> 240 </resh>
      <position>
        <x>-0.2</x>
        <y> 0.1 </y>
        <z> 0 </z>
      </position>  
      <orientation>
        <r>0</r>
        <p>0</p>
        <y>1.57 </y>
      </orientation>
    </virtualCamera> -->
    <rangeSensor>
      <name>sonar</name>
      <relativeTo>base</relativeTo>
      <range>10</range>
      <visible>1</visible>
      <position>
        <x>-0.3</x>
        <y>0</y>
        <z>0</z>
      </position>  
      <orientation>
        <r>0</r>
        <p>-1.6</p>
        <y>0</y>
      </orientation>
    </rangeSensor>
  </vehicle>

  <object>
    <name>terrain</name>
    <file>data2/terrain2/cirs_trident.osg</file>
    <position>
      <x> 0</x>
      <y> 0 </y>
      <z> 0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
    <offsetp>
      <x>-1.5</x>
      <y>-3.0</y>
      <z>0</z>
    </offsetp>
    <offsetr>
      <x> 3.1415</x>
      <y> 0</y>
      <z> -1.57 </z>
    </offsetr>
  </object>

  <object>
    <name> valve </name>
    <file>data2/objects2/valve.osg  </file>
    <position>
      <x> -1.05</x>
      <y> 1.0 </y>
      <z> 2.5 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
  </object>

  <rosInterfaces>
    <ROSOdomToPAT>
      <topic> /dataNavigator </topic>
      <vehicleName> girona500 </vehicleName>
    </ROSOdomToPAT>
    <PATToROSOdom>
      <topic> /uwsim/girona500_odom </topic>
      <vehicleName> girona500 </vehicleName>
    </PATToROSOdom>
    <ArmToROSJointState> 
	<topic>/uwsim/joint_state</topic>
	<vehicleName> girona500 </vehicleName>
    </ArmToROSJointState>
    <ROSJointStateToArm> 
	<topic>/uwsim/joint_state_command</topic>
	<vehicleName> girona500 </vehicleName>
    </ROSJointStateToArm>
<!--    <VirtualCameraToROSImage> 
      <cameraName>bowtech1</cameraName>
      <imageTopic> /uwsim/camera1 </imageTopic>
      <infoTopic> /uwsim/camera1_info </infoTopic>
    </VirtualCameraToROSImage> -->
    <RangeSensorToROSRange>
      <name>sonar</name>
      <topic> /uwsim/g500/range </topic>
      <rate>10</rate>
    </RangeSensorToROSRange>
  </rosInterfaces>
</UWSimScene>

=== snagappa/udg_pandora/scenes/pandoraLand.xml
<?xml version="1.0"?>

<!DOCTYPE UWSimScene SYSTEM "UWSimScene.dtd" >

<UWSimScene>
  <oceanState>
    <windx> 0.04 </windx>
    <windy> 0.04 </windy>
    <windSpeed> 12 </windSpeed>
    <depth> 1000 </depth>
    <reflectionDamping> 0.35 </reflectionDamping>
    <waveScale> 1e-7 </waveScale>
    <isNotChoppy> 0 </isNotChoppy>
    <choppyFactor> 2.5 </choppyFactor>
    <crestFoamHeight> 2.2 </crestFoamHeight>
    <oceanSurfaceHeight> 0 </oceanSurfaceHeight>
    <fog>
      <density> 0.1 </density>
      <color>
	<r>0</r>
	<g>0.05</g>
	<b>0.3</b>
      </color>
    </fog>
    <color>
      <r>0.0</r>
      <g>0.05</g>
      <b>0.3</b>
    </color>
    <attenuation>
      <r>0.015</r>
      <g>0.0075 </g>
      <b> 0.005 </b>
    </attenuation>
  </oceanState>
  <simParams>
    <disableShaders> 0 </disableShaders>
    <resw> 800 </resw>
    <resh> 600 </resh>
    <offsetp>
      <x>0</x>
      <y>0</y>
      <z>0</z>
    </offsetp>
    <offsetr>
      <x> 3.14</x>
      <y> 0</y>
      <z> -1.57 </z>
    </offsetr>
  </simParams>
  <camera>
    <freeMotion> 1 </freeMotion>
    <objectToTrack>girona500/base_link</objectToTrack> 
<!--    <objectToTrack>brac</objectToTrack> -->
    <fov> 60 </fov>
    <aspectRatio> 1.33 </aspectRatio>
    <near> 1 </near>
    <far> 10000 </far>
    <position>
      <x>-5</x>
      <y>-5</y>
      <z>8</z>
    </position> 
    <lookAt>
      <x>0</x>
      <y>0 </y>
      <z>0 </z>
    </lookAt>
  </camera>

  <vehicle>
    <name>girona500</name>
    <file>scenes/g500ARMPandora.urdf</file>
    <jointValues>
      <joint> 0.0 </joint>
      <joint> 1.5 </joint>  
      <joint> -2.5 </joint> 
      <joint> 0.0 </joint> 
      <joint> 0.0 </joint> 
    </jointValues>
    <position>
      <x> 0.0 </x>
      <y> 0.0 </y>
      <z> 0.0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>

    <virtualCamera>
      <name>left_down</name>
      <relativeTo>base</relativeTo>
      <resw> 640 </resw>
      <resh> 480 </resh>
      <position>
        <x>0.0</x>
        <y>-0.06</y>
        <z>0.0</z>
      </position>
      <orientation>
        <r>-3.14159</r>
        <p>0</p>
        <y>1.57</y>
      </orientation>
      <baseline> 0.0 </baseline>
      <frameId> stereo_down </frameId>
    </virtualCamera>
    <virtualCamera>
      <name>right_down</name>
      <relativeTo>base</relativeTo>
      <resw> 640 </resw>
      <resh> 480 </resh>
      <position>
        <x>0.0</x>
        <y>0.06</y>
        <z>0.0</z>
      </position>
      <orientation>
        <r>-3.14159</r>
        <p>0</p>
        <y>1.57</y>
      </orientation>
    <baseline>0.12</baseline>
    <frameId> stereo_down </frameId>
    </virtualCamera>

    <virtualCamera>
      <name>left_front</name>
      <relativeTo>base</relativeTo>
      <resw> 640 </resw>
      <resh> 480 </resh>
      <position>
        <x>0.0</x>
        <y>-0.06</y>
        <z>-0.7</z>
      </position>
      <orientation>
        <r>-1.57</r>
        <p>0</p>
        <y>1.57</y>
      </orientation>
      <baseline> 0.0 </baseline>
      <frameId> stereo_front </frameId>
    </virtualCamera>
    <virtualCamera>
      <name>right_front</name>
      <relativeTo>base</relativeTo>
      <resw> 640 </resw>
      <resh> 480 </resh>
      <position>
        <x>0.0</x>
        <y>0.06</y>
        <z>-0.7</z>
      </position>
      <orientation>
        <r>-1.57</r>
        <p>0</p>
        <y>1.57</y>
      </orientation>
    <baseline>0.12</baseline>
    <frameId> stereo_front </frameId>
    </virtualCamera>  

<rangeSensor>
      <name>sonar</name>
      <relativeTo>base</relativeTo>
      <range>10</range>
      <visible>0</visible>
      <position>
        <x>-0.3</x>
        <y>0</y>
        <z>0</z>
      </position>  
      <orientation>
        <r>0</r>
        <p>-1.6</p>
        <y>0</y>
      </orientation>
    </rangeSensor>
  </vehicle>

  <object>
    <name>terrain</name>
    <file>data2/objects2/land_obj.osg</file>

    <position>
      <x> 0</x>
      <y> 0 </y>
      <z> 6.0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
    <offsetp>
      <x>-1.5</x>
      <y>-3.0</y>
      <z>0</z>
    </offsetp>
    <offsetr>
      <x> 3.1415</x>
      <y> 0</y>
      <z> -1.57 </z>
    </offsetr>
  </object>

  <object>
    <name> panel </name>
	<file>data2/objects2/panel2.osg</file>
    <position>
      <x> -2.0 </x>
      <y> -2.0 </y>
      <z> 2.0 </z>
    </position>
    <orientation>
      <r>3.14</r>
      <p>0</p>
      <y>0.0</y>
    </orientation>
  </object>


 <object>
    <name> chain </name>
	<file>data2/objects2/chain.osg</file>
    <position>
      <x> 6.0 </x>
      <y> 8.0 </y>
      <z> 5.75 </z>
    </position>
    <orientation>
      <r>3.14</r>
      <p>0</p>
      <y>0</y>
    </orientation>
  </object>


  <object>
    <name> panel2 </name>
	<file>data2/objects2/panel2.osg</file>
    <position>
      <x> -8.0 </x>
      <y> 7.0 </y>
      <z> 5 </z>
    </position>
    <orientation>
      <r>3.14</r>
      <p>0</p>
      <y>1.57</y>
    </orientation>
  </object>


  <object>
    <name> stone1 </name>
	<file>data2/objects2/stone1.osg</file>
    <position>
      <x> -11.05</x>
      <y> 2.0 </y>
      <z> 5.5 </z>
    </position>
    <orientation>
      <r>3.14</r>
      <p>0</p>
      <y>0</y>
    </orientation>
  </object>

  <object>
    <name> stone2 </name>
	<file>data2/objects2/stone2.osg</file>
    <position>
      <x> -8.05</x>
      <y> 2.0 </y>
      <z> 6 </z>
    </position>
    <orientation>
      <r>3.14</r>
      <p>0</p>
      <y>0</y>
    </orientation>
  </object>

<object>
    <name> stone3 </name>
	<file>data2/objects2/stone1.osg</file>
    <position>
      <x> 12.05</x>
      <y> -2.0 </y>
      <z> 5.5 </z>
    </position>
    <orientation>
      <r>3.14</r>
      <p>0</p>
      <y>0</y>
    </orientation>
  </object>

  <object>
    <name> stone4 </name>
	<file>data2/objects2/stone2.osg</file>
    <position>
      <x> -6.05</x>
      <y> 2.0 </y>
      <z> 6 </z>
    </position>
    <orientation>
      <r>3.14</r>
      <p>0</p>
      <y>0</y>
    </orientation>
  </object>
  <rosInterfaces>
    <ROSOdomToPAT>
      <topic> /dataNavigator </topic>
      <vehicleName> girona500 </vehicleName>
    </ROSOdomToPAT>
    <PATToROSOdom>
      <topic> /uwsim/girona500_odom </topic>
      <vehicleName> girona500 </vehicleName>
    </PATToROSOdom>
    <ArmToROSJointState> 
	<topic>/uwsim/joint_state</topic>
	<vehicleName> girona500 </vehicleName>
    </ArmToROSJointState>
    <ROSJointStateToArm> 
	<topic>/uwsim/joint_state_command</topic>
	<vehicleName> girona500 </vehicleName>
    </ROSJointStateToArm>


    <VirtualCameraToROSImage>
      <cameraName>right_down</cameraName>
      <imageTopic> /stereo_down/right/image_raw </imageTopic>
      <infoTopic> /stereo_down/right/camera_info </infoTopic>
    </VirtualCameraToROSImage>
    <VirtualCameraToROSImage>
      <cameraName>left_down</cameraName>
      <imageTopic>/stereo_down/left/image_raw  </imageTopic>
      <infoTopic>/stereo_down/left/camera_info </infoTopic>
    </VirtualCameraToROSImage>
    

    <VirtualCameraToROSImage>
      <cameraName>right_front</cameraName>
      <imageTopic> /stereo_front/right/image_raw </imageTopic>
      <infoTopic> /stereo_front/right/camera_info </infoTopic>
    </VirtualCameraToROSImage>
    <VirtualCameraToROSImage>
      <cameraName>left_front</cameraName>
      <imageTopic>/stereo_front/left/image_raw  </imageTopic>
      <infoTopic>/stereo_front/left/camera_info </infoTopic>
    </VirtualCameraToROSImage>
    
    <RangeSensorToROSRange>
      <name>sonar</name>
      <topic> /uwsim/g500/range </topic>
      <rate>5</rate>
    </RangeSensorToROSRange>
  </rosInterfaces>
</UWSimScene>
